#pragma once

#include <driver/gpio.h>
#include <driver/i2c_master.h>
#include <driver/i2s_std.h>

#define KORVO_DISPLAY_WIDTH 800
#define KORVO_DISPLAY_HEIGHT 480
#define KORVO_DISPLAY_PIXEL_CLOCK_HZ (20 * 1000 * 1000)

#define KORVO_I2C_PORT I2C_NUM_0
#define KORVO_I2C_SDA GPIO_NUM_0
#define KORVO_I2C_SCL GPIO_NUM_1

#define KORVO_LCD_D0 GPIO_NUM_8
#define KORVO_LCD_D1 GPIO_NUM_9
#define KORVO_LCD_D2 GPIO_NUM_10
#define KORVO_LCD_D3 GPIO_NUM_11
#define KORVO_LCD_D4 GPIO_NUM_12
#define KORVO_LCD_D5 GPIO_NUM_13
#define KORVO_LCD_D6 GPIO_NUM_14
#define KORVO_LCD_D7 GPIO_NUM_15
#define KORVO_LCD_D8 GPIO_NUM_16
#define KORVO_LCD_D9 GPIO_NUM_17
#define KORVO_LCD_D10 GPIO_NUM_18
#define KORVO_LCD_D11 GPIO_NUM_19
#define KORVO_LCD_D12 GPIO_NUM_33
#define KORVO_LCD_D13 GPIO_NUM_34
#define KORVO_LCD_D14 GPIO_NUM_35
#define KORVO_LCD_D15 GPIO_NUM_36
#define KORVO_LCD_PCLK GPIO_NUM_40
#define KORVO_LCD_DE GPIO_NUM_43
#define KORVO_LCD_HSYNC GPIO_NUM_44
#define KORVO_LCD_VSYNC GPIO_NUM_45

#define KORVO_AUDIO_I2S_PORT I2S_NUM_0
#define KORVO_AUDIO_MCLK GPIO_NUM_NC
#define KORVO_AUDIO_BCLK GPIO_NUM_3
#define KORVO_AUDIO_WS GPIO_NUM_4
#define KORVO_AUDIO_DOUT GPIO_NUM_5
#define KORVO_AUDIO_DIN GPIO_NUM_6
#define KORVO_AUDIO_PA GPIO_NUM_7
#define KORVO_AUDIO_SAMPLE_RATE 16000
#define KORVO_AUDIO_CHANNELS 2
